networks:
  haus-netzwerk:
    external: true

services:
  room-09.1-rocketchat-app:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    container_name: room-09.1-rocketchat-app
    restart: unless-stopped
    environment:
      - PORT=3000
      - ROOT_URL=https://chat.delqhi.com
      - MONGO_URL=mongodb://room-09.2-mongodb-storage:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://room-09.2-mongodb-storage:27017/local
    networks:
      haus-netzwerk:
        ipv4_address: 172.20.0.91
    ports:
      - "3009:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/info || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s
